### PR TITLE
Build Statistics Page [Draft]

### PR DESCRIPTION
**Pull request by prawnydagrate**
Check this out

### CODE REVIEW

**Comment by safwansamsudeen** [comment]
@Python3-8 this looks beautiful! Thank you so much. 

Here is a pic. The first two charts are awesome. The third one is great too, but needs to be under a separate "Items" sections.
image

I think the fourth is WIP? You're correctly mentioning the number of reference items., but as discussed in DM - this should be "in", "out", "unavailable" and "reference".

**Comment by prawnydagrate** [comment]
oh so like instead of "For reference" in english it should be just "reference"?

**Comment by prawnydagrate** [comment]
oi test this

**Comment by prawnydagrate** [comment]
image
image
image

Hows this look

**Comment by prawnydagrate** [comment]
This is how it now looks with random test data. The charts are 350px by 350px instead of 300px by 300px, and they're also center-aligned. I don't think the center alignment looks great, so lmk if you want it back on the left

image
image
image
image

**Comment by safwansamsudeen** [comment]
@Python3-8 cool. 
image

What do you think about an h3 or something with each category of charts like `type`, and then have the label to All Items and Borrowed Items? We should probably use some CSS to group each two charts closer together then the rest - but you're better there than I am.

**Comment by prawnydagrate** [comment]
> @Python3-8 cool. 
> image
> 
> What do you think about an h3 or something with each category of charts like `type`, and then have the label to All Items and Borrowed Items? We should probably use some CSS to group each two charts closer together then the rest - but you're better there than I am.

sure I'll look into that

**Comment by safwansamsudeen** [comment]
@Python3-8 also I forgot about an important member chart 😬 - types of subscription. A lil complex to navigate, text in DM if necessary.

**Comment by prawnydagrate** [comment]
I've added the subscription type chart:
image

and fixed this chart which was buggy earlier (basically it wasn't even tracking the borrowed magazines because I was using a `Set` like an `Array`, and doing `number of magazines = set.length - number of books` just like on an `Array`, except `Set`s don't have `length`s, they only have `size`s; and also there **were** duplicates present because it turns out that no two JavaScript objects are equal, so a set can contain {1: 2} and a different {1: 2}, therefore I had to switch to using an array and deciding whether or not to add items using their `id`):
image

and I've also updated the transactions chart to use a time scale:
image

**Pull request merged**
